samples: samples.tsv
units: units.tsv

ref:
  # name used in snpeff database
  name: hg19
  genome: /vol/ref/aws-igenomes/Homo_sapiens/UCSC/hg19/BWAIndex/genome.fa
  # known variants (e.g. DBSNP)
  known-variants: /vol/ref/aws-igenomes/Homo_sapiens/GATK/hg19/bundle/dbsnp_138.hg19.vcf


filtering:
  # Set to true in order to apply machine learning based recalibration of
  # quality scores instead of hard filtering.
  vqsr: false
  hard:
    # hard filtering as outlined in GATK docs
    # (https://gatkforums.broadinstitute.org/gatk/discussion/2806/howto-apply-hard-filters-to-a-call-set)
    snvs:
      "QD < 2.0 || FS > 60.0 || MQ < 40.0 || MQRankSum < -12.5 || ReadPosRankSum < -8.0"
    indels:
      "QD < 2.0 || FS > 200.0 || ReadPosRankSum < -20.0"

processing:
  remove-duplicates: false
  # point to a bed file with e.g. captured regions if necessary,
  # see https://gatkforums.broadinstitute.org/gatk/discussion/4133/when-should-i-use-l-to-pass-in-a-list-of-intervals
  restrict-regions: ../raw/captured_regions.bed
  # If regions are restricted, use this to enlarge them in order to include
  # flanking areas.
  region-padding: 100

params:
  gatk:
    HaplotypeCaller: ""
    BaseRecalibrator: ""
    GenotypeGVCFs: ""
    VariantRecalibrator: ""
  picard:
    MarkDuplicates: "REMOVE_DUPLICATES=true"
  cutadapt:
    pe: ""
    se: ""
  trimmomatic:
    pe:
      trimmer: 
        - "ILLUMINACLIP:../raw/primers_adapters.fasta:2:30:10"
        - "LEADING:3"
        - "TRAILING:3"
        - "SLIDINGWINDOW:4:15"
        - "MINLEN:36"
    se:
      trimmer: 
        - "ILLUMINACLIP:../raw/primers_adapters.fasta:2:30:10"
        - "LEADING:3"
        - "TRAILING:3"
        - "SLIDINGWINDOW:4:15"
        - "MINLEN:36"
